### ISSUE TITLE
Furk it addon request

### ISSUE THREAD

**Issue by kodiultimate** [a4k-openproject/json.openplayers#1]
Hi,

Could someone please generate json file for Furk it addon ?
Here is the link

https://github.com/Tikipeter/repository.tikipeter/tree/master/zip/plugin.video.furkit

**Comment by SerpentDrago** [comment]
Going to need info to make a player with . 

Please favorite , a movie search result  , the search menu / etc 

then send that favorites.xml kodi makes .

**Comment by SerpentDrago** [comment]
also provide a full debug log  while you use the addon and send

**Comment by SerpentDrago** [comment]
If you can provide a temp / dev account that would be great also

**Comment by SerpentDrago** [comment]
also the latest dev is in  https://github.com/Tikipeter/repository.tikipeter/tree/master/zip/plugin.video.fen

from the same repo
