### ISSUE TITLE
Request to add 2 addons to your json.openplayers.

### ISSUE THREAD

**Issue by techecoyote** [a4k-openproject/json.openplayers#17]
Greetings, love the work you're doing for the kodi community. Thank you for all your effort. I use
your openscrapers  & your open meta in my addons / build. They're outstanding...

I have 2 addons, plugin.video.tiger (venom fork) & plugin.video.sabertooth (fen fork), that I would
like added to your json library download. I don't know if it is possible but I thought I would ask.

Thanx again for all your hard work, time & effort!!!!

**Comment by drinfernoo** [comment]
Do you have a repo address for them?

**Comment by techecoyote** [comment]
Is a repo address needed to add them to the Openmeta .json players?

**Comment by drinfernoo** [comment]
@techecoyote Well, how can we add them if we don't have the add-ons to test with?

**Comment by techecoyote** [comment]
Gotcha, my misunderstanding...
http://xjc.000webhostapp.com/REPO/repository.X-Zot-Iks-19.08.25.zip
Hope this helps. Thank You..

**Comment by techecoyote** [comment]
Wanted to find out the status of adding my 2 addons?
plugin.video.tiger (venom fork)
plugin.video.sabertooth (fen fork)
Thank you...
