### ISSUE TITLE
Request to add plexkodiconnect and hbogoeu players

### ISSUE THREAD

**Issue by webmaher** [a4k-openproject/json.openplayers#23]
Hi
thank you for your great addon... is it possible to also add player for:
HBOGOeu video addon https://forum.kodi.tv/showthread.php?tid=339798
PLEXkodiconnect https://forum.kodi.tv/showthread.php?tid=262621

Thanks and
                      Best Regards

**Comment by drinfernoo** [comment]
There are players for both of these now :+1:

**Comment by webmaher** [comment]
Hi
Thank you very much but i cant find HBOGO player...

 I always add movies or series in library with OpenMeta and this is work OK. Plexkodiconnect player is my default...When i start movies they always found 2 or 3 movies (same name) and then i choose which one to play....  First is usally 1080p (from folder Movies) Second is usally 4k (from folder Movies - 4k) Third is usally 4k remux (from folder Movies - 4k Remux)
Is possible to see also name of the folders or maybe name of the movie file?
When I start serie they always found only one with 1080 quality even if i have also 4k quality...
I have two folders with name: SeriesSeries - 4k
Is possible to see also name of the folders or maybe name of the serie file?
And also is it possible that if some movies or series dont found in Plex (default player) then automatically start Scrubs v2 player?
Thanks again for this great addon
and Best Regards                               janKO

    On Friday, January 3, 2020, 04:45:21 AM GMT+1, drinfernoo <notifications@github.com> wrote:  
 
 
There are players for both of these now 👍

**Comment by drinfernoo** [comment]
Oh man, I forgot to push it! Give me five minutes and I will!

**Comment by webmaher** [comment]
OK it works but i must change this at begining:
  "plugin"       : "plugin.video.hbogoeu",  "priority"     : 300,  "id"           : "search.hbogoeu",
What about my questions for plexkodiconnect.... is possible or not?
Thanks :-)

    On Friday, January 3, 2020, 05:39:51 PM GMT+1, drinfernoo <notifications@github.com> wrote:  
 
 
Oh man, I forgot to push it! Give me five minutes and I will!

**Comment by drinfernoo** [comment]
There is already a PKC player, but what did you have to change in the hGO EU player?

**Comment by webmaher** [comment]
"plugin" : "plugin.video.hgoeu",

change to
  "plugin"       : "plugin.video.hbogoeu",


and
 "id" : "search.hgoeu",

change to
 "id"           : "search.hbogoeu",


I know PKC work but for series find only HD title and not also 4k title ... so please read again what already wrote to you ... sorry for my english :-(
Thanks


    On Friday, January 3, 2020, 10:48:19 PM GMT+1, drinfernoo <notifications@github.com> wrote:  
 
 
There is already a PKC player, but what did you have to change in the hGO EU player?

**Comment by drinfernoo** [comment]
Ah, I missed a typo, is what you're saying. I just fixed the `plugin` and `id` fields, and pushed the new player file.

Would you please open a separate issue regarding any troubles you're having with the PKC player? They are a bit scattered here, and I can't quite figure out what you're asking for.

**Comment by webmaher** [comment]
OK, here we go
Plexkodiconnect player issue · Issue #27 · a4k-openproject/json.openplayers

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Plexkodiconnect player issue · Issue #27 · a4k-openproject/json.openplayers

Plexkodiconnect player is my default and work ... I have 3 movies folder: Movies Movies - 4k Movies - 4k Remux I...
 |

 |

 |


Thanks for your help :-)



    On Saturday, January 4, 2020, 12:42:31 AM GMT+1, drinfernoo <notifications@github.com> wrote:  
 
 
Ah, I missed a typo, is what you're saying. I just fixed the plugin and id fields, and pushed the new player file.

Would you please open a separate issue regarding any troubles you're having with the PKC player? They are a bit scattered here, and I can't quite figure out what you're asking for.
