### ISSUE TITLE
Embycon player broken with 1.9.54

### ISSUE THREAD

**Issue by garymc** [a4k-openproject/json.openplayers#25]
A recent Embycon update broke the json player as the menu structure changed. 

Embycon 1.9.54 is the current version in the Emby repository

Instead of navigating directly to top level menu items

All - Movies A-Z
or
All - TV Show A-Z

The player will need to go to deeper to reach the A-Z items.

Global Lists > Movies > Movies - A-Z
or
Global Lists > TV Shows > TV Shows - A-Z

**Comment by drinfernoo** [comment]
Can you try the latest player?

**Comment by garymc** [comment]
It's working now apart from movies and TV shows with parentheses in their titles.

I'm not sure if that's a new bug caused by this fix or if it existed in previous versions of the player.

I can log it as a separate issue if needed.

**Comment by drinfernoo** [comment]
It's likely an issue that would've been present in the previous version of the player as well. No need to open another issue... I'll try and see about getting those working as well.

**Comment by drinfernoo** [comment]
If you're also using TheMovieDb Helper from @jurialmunkey, then it would be great if you'd try the updated EmbyCon player for that too: https://github.com/a4k-openproject/json.openplayers/blob/tmdbhelper/embycon.json

**Comment by juanma-cvega** [comment]
hi,
I'm trying to use TheMovieDb Helper with EmbyCon and it's not working for me. It always says 'Item not found'. Can I attach here the logs?

**Comment by juanma-cvega** [comment]
This is the log file.
[kodi.log](https://github.com/a4k-openproject/json.openplayers/files/4207262/kodi.log)

**Comment by drinfernoo** [comment]
@juanma-cvega You didn't actually put a link.

**Comment by drinfernoo** [comment]
@juanma-cvega There are no fatal errors in that log. What are you experiencing?

**Comment by juanma-cvega** [comment]
It just says, 'EmbyCon: Item not found' and then it shows a dialog to choose a player from

**Comment by drinfernoo** [comment]
Then that item isn't being found by EmbyCon... probably the player is trying to call the wrong path or something similar.

**Comment by juanma-cvega** [comment]
The videos I've tried to play are videos i tested before that are working. I'm new to Emby and the Emby addons in Kodi so I'm not discarding any wrong configuration. But from the logs it's quite difficult to know what calls The MovieDb Helper addon is doing.

**Comment by drinfernoo** [comment]
@juanma-cvega Unfortunately, I don't have Emby... which makes it super hard to make and/or debug a player file for it 😩

**Comment by juanma-cvega** [comment]
i reached out to the developer of the EmbyCon player and he replied with an example of what the player would look like based on the Netflix one. But, to be honest, I cannot make much sense of what would be the final player based on his response. @drinfernoo would you be able to help based on his answer? The link to his reply is [here](https://github.com/faush01/plugin.video.embycon/issues/94).

**Comment by drinfernoo** [comment]
@juanma-cvega I really can't commit to "getting it working", since I have *literally* no way to test or debug it... But it appears he's already given you the path, and indicated where you need to fill in your own details. It also appears from that path that your player file will include details that are specific to you. That means there won't likely be any way to make a "generic" player file for EmbyCon that will work for every user.

I would consider looking at the current player file, and changing the path to match his, with your own details. Beyond that, I can't really help much more.
