### ISSUE TITLE
Add player for Shadow addon

### ISSUE THREAD

**Issue by cgcgcgcgcg** [a4k-openproject/json.openplayers#30]
It's similar to FoxyStreams, can be found in The Crew, Ezzer-Mac and more repos.
Thanks in advance if it can be done.

**Comment by brentonv** [comment]
Will it work? "The add-on works a bit differently by giving a web address to open with a Browser and a code to enter"

**Comment by cgcgcgcgcg** [comment]
> Will it work? "The add-on works a bit differently by giving a web address to open with a Browser and a code to enter"

I don't know what you mean.
It works like Foxystreams (which already has a player) and I never saw a browser or a code involved in Shadow.
I authorized my debrid service and it works fine -gives more sources than Foxystreams too.

**Comment by drinfernoo** [comment]
Shadow doesn't work like FoxyStreams. There's many, many differences, so a similar player won't work.

Shadow needs to have a path figured out, but no one has looked into it that I know of.

**Comment by brentonv** [comment]
@cgcgcgcgcg looks like @drinfernoo added it :smiley: https://github.com/a4k-openproject/json.openplayers/commit/e0ecaf35298a8a2118acbea3b18d5c3d2ab16a7e

**Comment by brentonv** [comment]
@cgcgcgcgcg  looks like @drinfernoo  added it :smiley: -->https://github.com/a4k-openproject/json.openplayers/commit/e0ecaf35298a8a2118acbea3b18d5c3d2ab16a7e

**Comment by cgcgcgcgcg** [comment]
Thank you.

**Comment by brentonv** [comment]
Yeah thanks @drinfernoo :smiley:
