### ISSUE TITLE
Update tmdbplayers with the EmbyCon player from TheMovieDB Helper

### ISSUE THREAD

**Issue by juanma-cvega** [a4k-openproject/json.openplayers#39]
I created an Embycon player with different options for TheMovieDB Helper that got merged into the main branch of the addon. Would it be possible to add it to the bundle, please? It may break the addon for anyone using the player posted here so maybe it would need to be renamed to something else. There are 2 players actually, one of them based on a small modification I did to the Embycon addon (it got also pushed to the main branch) so the renaming of the main file could follow the same approach as that one.

**Comment by SerpentDrago** [comment]
submit a pr
