### ISSUE TITLE
Custom addon based on exodus

### ISSUE THREAD

**Issue by pewkodi** [a4k-openproject/json.openplayers#40]
i am trying to use my custom based add on with moviedb helper. i was able to copy the exodus redux file and point to my addon in the json file. my question is if i search for a movie and save it as a favorite it will work and begin to search for links but if i use the app it will not bring up the preparing links dialog box. 

is there something i need to add in my addon for it to work properly?

Thanks

**Comment by drinfernoo** [comment]
Hard to say; it's your add-on.

**Comment by pewkodi** [comment]
Well here is the log: http://ix.io/2lSB

**Comment by drinfernoo** [comment]
I don't really think that this is an issue for this repo. That log is far too cluttered to be useful, and this clearly seems like an issue with your add-on in some way.

**Comment by pewkodi** [comment]
i was able to figure it out. there was an old function causing the problem. Thanks. control.modertor was the cause.
