### ISSUE TITLE
TheMovieDB Helper Venom players

### ISSUE THREAD

**Issue by mrgsi** [a4k-openproject/json.openplayers#53]
I've noticed (using Aeon-Nox-Silvo with Kodi 19) that Venom sources list looks crappy in the smaller Dialog view (the double lines overlap), but look good in Directory view (full screen). However, the venom players seem to default to Dialog view regardless of what the Venom settings are (Dialog or Directory). Is there any way to code the venom players into forcing Directory view mode?

**Comment by jmh2002** [comment]
I'm not sure that this is the totally correct way to do it (and I see that other player files don't have this) but in the player I changed the very end of the text string from select=0 to select=1

I think that is what fixed it. It was a while ago so my memory might not be perfect.
