### ISSUE TITLE
a4kStreaming episode

### ISSUE THREAD

**Issue by djdirty60** [a4k-openproject/json.openplayers#73]
Good day,

a4kStreaming for the episodes does not work via TheMovieDb Helper. He does take movies.  
Can someone take a look at that?  

Thank you in advance

**Comment by drinfernoo** [comment]
Is there an error?

**Comment by djdirty60** [comment]
Yes he doesn't take all episodes, one series does and the other series doesn't

**Comment by drinfernoo** [comment]
Have you checked the log?

**Comment by djdirty60** [comment]
Yes he can find one series in a4kStreaming via TheMovieDb Helper and the other cannot.

**Comment by drinfernoo** [comment]
Check your log to see if there are errors: https://kodi.wiki/view/Log_file/Easy

I would recommend uploading the log so we can investigate further as well.

**Comment by djdirty60** [comment]
https://paste.kodi.tv/yugezezete

**Comment by djdirty60** [comment]
Has the problem already been found?

thanks in advance

https://paste.kodi.tv/akekuqekum

**Comment by xyzfre** [comment]
a4kStreaming is definitely a gem, will be a plus if this issue could be addressed

**Comment by drinfernoo** [comment]
The developer tested the player, and it's working for him.

**Comment by djdirty60** [comment]
Foreign
